# Workflow name
name: Backend-Continuous-Integration

# Triggers for the workflow
on:      
  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - main
 # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

# Jobs defined in the workflow
jobs:
  backend-lint-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - name: Checkout code
      uses: actions/checkout@v3    
    - name: Install pipenv
      run: pip install pipenv
    - name: Install dependencies
      run: pipenv install --dev
    - name: Run lint
      run: |
        pipenv run lint
  backend-test-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - name: Checkout code
      uses: actions/checkout@v3    
    - name: Install pipenv
      run: pip install pipenv
    - name: Install dependencies
      run: pipenv install --dev
    - name: Test with pytest
      run: |
        pipenv run test
  backend-build-job:
    runs-on: ubuntu-latest
    needs: [backend-lint-job, backend-test-job] #dependent job
    defaults:
      run:
        working-directory: ./backend
    steps:
    - name: Checkout code
      uses: actions/checkout@v3    
    - 
      name: Docker build
      run: |
        docker build -t mp-backend:latest .
        